### ISSUE TITLE
[1.12.2] Crafttweaker integration broke again

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Practical-Logistics-2#74] opened 2018-11-03 14:04 UTC
Hello!
I'm trying to add CT recipe for Forging Hammer like following:
```javascript
import mods.logistics.hammer as Forging;
Forging.addRecipe(ingot_tempered * 8, item_elemental_core);
```
(these are global variables) and I get this error:
```
ERROR: no such member: hammer
```
I'm using `Forge-14.23.4.2759`, `CraftTweaker2-1.12.2-4.1.9`, `SonarCore-1.12.2-5.0.16-16` and `practicallogistics2-1.12.2-3.0.4`.

**Comment by ghost** [comment] 2018-11-26 22:24
This just started to show up on me as well even on the new version of forge

@SonarSonic

**Comment by justinrusso** [comment] 2018-11-27 03:31
I'm getting `[CHAT] ERROR: system: hammer is already defined in that package`.

This looks to be caused by the Hammer class being registered twice to CraftTweaker.
Prior to 3.0.5, the issue was as mentioned above, and was caused by the hammer class being registered far too late for anything done in CraftTweaker. Adding the `@ZenRegister` annotation will register it at the proper time now, but its also being registered later during postLoad https://github.com/SonarSonic/Practical-Logistics-2/blob/37f8e055c54638736a1b70cdbecea632e5d3060b/src/main/java/sonar/logistics/PL2.java#L115

I would recommend removing https://github.com/SonarSonic/Practical-Logistics-2/blob/37f8e055c54638736a1b70cdbecea632e5d3060b/src/main/java/sonar/logistics/PL2.java#L114-L117 as well as https://github.com/SonarSonic/Practical-Logistics-2/blob/37f8e055c54638736a1b70cdbecea632e5d3060b/src/main/java/sonar/logistics/integration/minetweaker/CraftTweakerIntegration.java#L24

**Comment by Sunekaer** [comment] 2018-11-28 15:18
Hey 

Im also having this issue with "[CHAT] ERROR: system: hammer is already defined in that package"

**Comment by SonarSonic** [comment] 2018-12-01 17:25
Fixed in dev

**Closed as completed by SonarSonic** 2018-12-01 17:25 UTC
